# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.srcs/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0.xci
# IP: The module: 'Proximity_Alarm_bd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proximity_Alarm_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proximity_Alarm_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proximity_Alarm_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.srcs/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0.xci
# IP: The module: 'Proximity_Alarm_bd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proximity_Alarm_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proximity_Alarm_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proximity_Alarm_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
