# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_master.xdc

# Block Designs: bd/Proximity_Alarm_bd/Proximity_Alarm_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd || ORIG_REF_NAME==Proximity_Alarm_bd} -quiet] -quiet

# IP: bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_processing_system7_0_0/Proximity_Alarm_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd_processing_system7_0_0 || ORIG_REF_NAME==Proximity_Alarm_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_ps7_0_axi_periph_0/Proximity_Alarm_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==Proximity_Alarm_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_rst_ps7_0_50M_0/Proximity_Alarm_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==Proximity_Alarm_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_piezo_buzzer_0_0/Proximity_Alarm_bd_piezo_buzzer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd_piezo_buzzer_0_0 || ORIG_REF_NAME==Proximity_Alarm_bd_piezo_buzzer_0_0} -quiet] -quiet

# IP: bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_UART_MAXSONAR_0_0/Proximity_Alarm_bd_UART_MAXSONAR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd_UART_MAXSONAR_0_0 || ORIG_REF_NAME==Proximity_Alarm_bd_UART_MAXSONAR_0_0} -quiet] -quiet

# IP: bd/Proximity_Alarm_bd/ip/Proximity_Alarm_bd_auto_pc_0/Proximity_Alarm_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Proximity_Alarm_bd_auto_pc_0 || ORIG_REF_NAME==Proximity_Alarm_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/ECE520_SOC/ECE520_SandBox/Ultrasonic_Proximity_Alarm_soc_re/Ultrasonic_Proximity_Alarm_soc_re.gen/sources_1/bd/Proximity_Alarm_bd/Proximity_Alarm_bd_ooc.xdc
